# Generated by Django 4.0.4 on 2022-10-17 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hero.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('main_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pro_img', models.ImageField(blank=True, upload_to=hero.models.profile_img_upload)),
                ('bio', models.TextField(default='Hello I Am Busy Now a Days')),
            ],
        ),
    ]
