# Generated by Django 4.0.4 on 2022-10-19 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import hero.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userdata',
            managers=[
                ('evolved', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='followers',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='following',
            field=models.TextField(default='[]'),
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_img', models.ImageField(blank=True, upload_to=hero.models.post_url)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
