# Generated by Django 4.0.4 on 2022-10-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_alter_userdata_managers_userdata_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='foll_pending',
            field=models.TextField(default='[]'),
        ),
    ]
