# Generated by Django 4.0.4 on 2022-10-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_poster_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
