# Generated by Django 4.0.4 on 2022-10-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_poster_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='peoples',
            field=models.TextField(default='[]'),
        ),
    ]
