# Generated by Django 4.0.4 on 2022-10-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0006_poster_peoples'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='activity',
            field=models.TextField(default='[]'),
        ),
    ]
