# Generated by Django 4.0.4 on 2022-10-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0007_userdata_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(max_length=500)),
                ('users', models.TextField()),
                ('messages', models.TextField(default='[]')),
            ],
        ),
    ]
